language: node_js
node_js:
  - "node"
before_install:
  - npm i -g npm@6.9.0
  - npm i -g mocha

services: 
  - postgresql

before_script:
  - psql -c 'create database banka_test_db;' -U postgres

after_script:
  - codeclimate-test-reporter < lcov.info

env:
  global:
    - JWTKEY="123i50M3TR1CB0D135"

after_success: 
  - npm run coverage 